# Generated by Django 6.0.5 on 2026-05-13 03:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowed_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='good', max_length=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrowed_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='borrowed_books.borrowedbook')),
            ],
            options={
                'verbose_name': 'Returned Book',
                'verbose_name_plural': 'Returned Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
