# Generated by Django 6.0.5 on 2026-05-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowed_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
