# Generated by Django 6.0.5 on 2026-05-14 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowed_books', '0002_alter_borrowedbook_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrow_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
